export const translations = {
  fr: {
    common: {
      dashboard: "Tableau de Bord",
      properties: "Propriétés",
      tenants: "Locataires",
      payments: "Paiements",
      whatsapp: "Gestion WhatsApp",
      map: "Carte",
      users: "Utilisateurs",
      reports: "Rapports",
      settings: "Paramètres",
      logout: "Déconnexion",
      add: "Ajouter",
      edit: "Modifier",
      delete: "Supprimer",
      save: "Enregistrer",
      cancel: "Annuler",
      search: "Rechercher",
      status: "Statut",
      actions: "Actions",
      loading: "Chargement...",
      success: "Opération réussie",
      error: "Une erreur est survenue",
      confirmDelete: "Êtes-vous sûr de vouloir supprimer cet élément ?",
      mru: "MRU",
      role: "Rôle",
      username: "Nom d'utilisateur",
      password: "Mot de passe",
      active: "Actif",
      inactive: "Inactif",
      admin: "Administrateur",
      operator: "Opérateur",
    },
    dashboard: {
      totalProperties: "Total Propriétés",
      rentedProperties: "Propriétés Louées",
      totalRent: "Loyer Total",
      totalDebt: "Dette Totale",
      activeUsers: "Utilisateurs Actifs",
      monthlyReceipts: "Reçus Mensuels",
    },
    property: {
      id: "ID Propriété",
      name: "Nom",
      province: "Wilaya",
      region: "Moughataa",
      rent: "Loyer",
      type: "Type",
      area: "Superficie (m²)",
      rooms: "Chambres",
      description: "Description",
      status: {
        rented: "Loué",
        available: "Disponible",
        maintenance: "Maintenance",
      },
      paymentStatus: {
        paid: "Payé",
        unpaid: "Non Payé",
        overdue: "En Retard",
        doubtful: "Douteux",
      },
      types: {
        apartment: "Appartement",
        villa: "Villa",
        shop: "Commerce",
        office: "Bureau",
        warehouse: "Entrepôt",
      }
    },
    tenant: {
      name: "Nom du Locataire",
      whatsapp: "WhatsApp",
      rating: "Évaluation",
      notes: "Notes",
      ratings: {
        excellent: "Excellent",
        good: "Bon",
        average: "Moyen",
        bad: "Mauvais",
      }
    },
    payment: {
      amount: "Montant",
      date: "Date",
      method: "Mode de Paiement",
      operator: "Opérateur",
      methods: {
        cash: "Espèces",
        bank: "Virement Bancaire",
        check: "Chèque",
        mobile: "Paiement Mobile",
      }
    },
    whatsapp: {
      sendReminder: "Envoyer Rappel",
      messageTemplates: "Modèles de Messages",
      clientsByStatus: "Clients par Statut",
    }
  },
  ar: {
    common: {
      dashboard: "لوحة القيادة",
      properties: "العقارات",
      tenants: "المستأجرون",
      payments: "المدفوعات",
      whatsapp: "إدارة واتساب",
      map: "الخريطة",
      users: "المستخدمين",
      reports: "التقارير",
      settings: "الإعدادات",
      logout: "تسجيل الخروج",
      add: "إضافة",
      edit: "تعديل",
      delete: "حذف",
      save: "حفظ",
      cancel: "إلغاء",
      search: "بحث",
      status: "الحالة",
      actions: "الإجراءات",
      loading: "جاري التحميل...",
      success: "تمت العملية بنجاح",
      error: "حدث خطأ ما",
      confirmDelete: "هل أنت متأكد من حذف هذا العنصر؟",
      mru: "أوقية",
      role: "الدور",
      username: "اسم المستخدم",
      password: "كلمة المرور",
      active: "نشط",
      inactive: "غير نشط",
      admin: "مدير",
      operator: "مشغل",
    },
    dashboard: {
      totalProperties: "إجمالي العقارات",
      rentedProperties: "العقارات المؤجرة",
      totalRent: "إجمالي الإيجار",
      totalDebt: "إجمالي الديون",
      activeUsers: "المستخدمون النشطون",
      monthlyReceipts: "الإيصالات الشهرية",
    },
    property: {
      id: "معرف العقار",
      name: "الاسم",
      province: "الولاية",
      region: "المقاطعة",
      rent: "الإيجار",
      type: "النوع",
      area: "المساحة (م²)",
      rooms: "الغرف",
      description: "الوصف",
      status: {
        rented: "مؤجر",
        available: "متاح",
        maintenance: "صيانة",
      },
      paymentStatus: {
        paid: "مدفوع",
        unpaid: "غير مدفوع",
        overdue: "متأخر",
        doubtful: "مشكوك فيه",
      },
      types: {
        apartment: "شقة",
        villa: "فيلا",
        shop: "محل تجاري",
        office: "مكتب",
        warehouse: "مستودع",
      }
    },
    tenant: {
      name: "اسم المستأجر",
      whatsapp: "واتساب",
      rating: "التقييم",
      notes: "ملاحظات",
      ratings: {
        excellent: "ممتاز",
        good: "جيد",
        average: "متوسط",
        bad: "سيئ",
      }
    },
    payment: {
      amount: "المبلغ",
      date: "التاريخ",
      method: "طريقة الدفع",
      operator: "المشغل",
      methods: {
        cash: "نقداً",
        bank: "تحويل بنكي",
        check: "شيك",
        mobile: "دفع عبر الهاتف",
      }
    },
    whatsapp: {
      sendReminder: "إرسال تذكير",
      messageTemplates: "قوالب الرسائل",
      clientsByStatus: "العملاء حسب الحالة",
    }
  }
};

export const mauritaniaData = {
  provinces: [
    { id: "nouakchott_ouest", name: { fr: "Nouakchott Ouest", ar: "نواكشوط الغربية" }, regions: ["Tevragh Zeina", "Ksar", "Sebkha"] },
    { id: "nouakchott_nord", name: { fr: "Nouakchott Nord", ar: "نواكشوط الشمالية" }, regions: ["Dar Naim", "Teyarett", "Toujounine"] },
    { id: "nouakchott_sud", name: { fr: "Nouakchott Sud", ar: "نواكشوط الجنوبية" }, regions: ["Arafat", "El Mina", "Riyad"] },
    { id: "nouadhibou", name: { fr: "Dakhlet Nouadhibou", ar: "داخلت نواذيبو" }, regions: ["Nouadhibou", "Chami"] },
    { id: "trarza", name: { fr: "Trarza", ar: "اترارزة" }, regions: ["Rosso", "Boutilimit", "R'Kiz", "Mederdra"] },
    { id: "brakna", name: { fr: "Brakna", ar: "لبراكنة" }, regions: ["Aleg", "Boghé", "M'Bagne", "Bababe", "Mal"] },
    { id: "gorgol", name: { fr: "Gorgol", ar: "كوركول" }, regions: ["Kaédi", "M'Bout", "Monguel", "Lexeiba"] },
    { id: "guidimaka", name: { fr: "Guidimaka", ar: "كيدي ماغا" }, regions: ["Sélibaby", "Ghabou", "Ould Yengé", "Gouraye"] },
    { id: "assaba", name: { fr: "Assaba", ar: "لعصابة" }, regions: ["Kiffa", "Kankossa", "Barkéwol", "Boumdeid", "Guérou"] },
    { id: "hodh_chargui", name: { fr: "Hodh Ech Chargui", ar: "الحوض الشرقي" }, regions: ["Néma", "Amourj", "Djigueni", "Timbedra", "Bassiknou"] },
    { id: "hodh_gharbi", name: { fr: "Hodh El Gharbi", ar: "الحوض الغربي" }, regions: ["Ayoun el Atrous", "Kobeni", "Tamchekett", "Tintane"] },
    { id: "tagant", name: { fr: "Tagant", ar: "تكانت" }, regions: ["Tidjikja", "Tichit", "Moudjéria"] },
    { id: "adrar", name: { fr: "Adrar", ar: "آدرار" }, regions: ["Atar", "Chinguetti", "Ouadane", "Aoujeft"] },
    { id: "inchiri", name: { fr: "Inchiri", ar: "إينشيري" }, regions: ["Akjoujt", "Benichab"] },
    { id: "tiris_zemmour", name: { fr: "Tiris Zemmour", ar: "تيرس زمور" }, regions: ["Zouérate", "Fdérik", "Bir Moghrein"] },
  ]
};
